nens/threedi-modelchecker

threedi_modelchecker/checks/other.py
closes https://github.com/nens/ThreeDiToolbox/issues/497
sqlalchemy 1.1.18 doesn't support this query but sqlalchemy 1.3.1 does. This fixes the query for sqlalchemy 1.1.18
=> Fix query for ConnectionNodesLength

threedi_modelchecker/threedi_model/models.py
I encountered this issue when I was writing tests for `threedigrid-builder`: geometry columns require `management=True` if the backend is sqlite. Otherwise you cannot create/destroy geometry columns.
See:
https://geoalchemy-2.readthedocs.io/en/latest/spatialite_tutorial.html#declare-a-mapping
I don't think that PostGIS is broken by this, because PostGIS also supports the AddGeometryColumn/DiscardGeometryColumn commands.
=> Add management=True to geometry columns

CHANGES.rst, setup.py, tests/conftest.py, tests/factories.py, tests/test_checks_base.py, tests/test_model_checks.py, threedi_modelchecker/checks/base.py, threedi_modelchecker/config.py, threedi_modelchecker/model_checks.py, threedi_modelchecker/threedi_database.py, threedi_modelchecker/threedi_model/models.py
This adds a `FileExistsChecker` along with configurations for all file fields in the SQLite.
Implementing this was quite tricky, because a `Checker` has no clue of its context, so it can't interpret paths relative to the sqlite. An additional complexity is that in the threedi-api the paths have no meaning and we have to come up with a different method of saying whether a raster is there or not.
I solved this by adding a `Context` object to the `ModelChecker`. The context contains 1) a list of available rasters (for the API) and 2) a base path, which is the directory containing the sqlite. The context is stuck to the session and picked up by the checker.
=> [Done] Add a checker for file existence

CHANGES.rst, README.rst, requirements-dev.txt, requirements.txt, threedi_modelchecker/checks/base.py, threedi_modelchecker/checks/factories.py, threedi_modelchecker/checks/other.py, threedi_modelchecker/config.py, threedi_modelchecker/exporters.py, threedi_modelchecker/model_checks.py, threedi_modelchecker/schema.py, threedi_modelchecker/scripts.py
This adds the option to specify a loglevel (`level="warning"`) and error_code (`error_code=12`) for specific checks.
I used the new levels (just for testing) for the enum checks. Now, a wrong sewerage_type results in a WARNING and a wrong zoom_category in an INFO.
I also fixed the command-line client:
- removed the (non-working) "summarize" option
- there was a formatter in place, but it wasn't used. Instead the raw python tuples were dumped. I enabled it and tweaked the output. It now looks like this:
```
(...)
E0000 (row 36) Value in v2_pipe.friction_type is invalid, expected one of [CHEZY, MANNING]
E0000 (row 37) Value in v2_pipe.friction_type is invalid, expected one of [CHEZY, MANNING]
E0000 (row 38) Value in v2_pipe.friction_type is invalid, expected one of [CHEZY, MANNING]
E0000 …
```
=> Add log levels (INFO and WARNING) and error codes

CHANGES.rst, threedi_modelchecker/simulation_templates/boundaries/extractor.py
New format is:
```
{
"id": 3, (spatialite id from boundary table)
"type": "1D",
"interpolate": false,
"values": [
[0, -2.4],
[1300, 0,3],
[3000, 1.2],
[3600, 0]
]
}
```
=> [DONE] Added extra fields to boundary JSON file

CHANGES.rst, tests/factories.py, tests/test_simulaton_templates.py, threedi_modelchecker/migrations/versions/0200_initial.py, threedi_modelchecker/threedi_model/constants.py
This implements https://github.com/nens/threedi/blob/master/lib/threedi-tools/threedi_tools/migrations/0172_auto__del_v2initialwaterlevel__del_field_v2orifice_max_capacity__del_f.py#L11  so that we can also accept version 173 (not sure about the off-by-one here)
=> Also accept version 173

tests/factories.py, tests/test_simulaton_templates.py, threedi_modelchecker/config.py, threedi_modelchecker/migrations/versions/0206_control_structures.py, threedi_modelchecker/simulation_templates/structure_controls/extractor.py, threedi_modelchecker/threedi_model/constants.py, threedi_modelchecker/threedi_model/models.py
This enforces a more strict datamodel for the controls. There are checks on nullability, enums, and foreign key references. Note that the nullability and enum checks are automatically generated just by changing the data model.
There is potentially a lot more validations to do:
- action_value and action_tables fields
- sum of weights must be 1
- certain combinations of action_type and structure_type
There were ~13 models with weight=NULL, I migrated these to weight=1.0 (because all these models had just 1 structure control map)
=> Done: Some checks for control structures

CHANGES.rst, threedi_modelchecker/config.py
Only 2 models (out of 905) use it.
=> Add dem_obstacle_detection check

CHANGES.rst, threedi_modelchecker/config.py, threedi_modelchecker/simulation_templates/initial_waterlevels/extractor.py
The issue was that empty strings were interpreted as "no file" in the modelchecker, but not in the template worker.
The water_level_ini_type is compulsory, I checked all existing models and each of them has the water_level_ini_type filled if initial_waterlevel is supplied.
The same story for groundwater, only there the check on initial_groundwater_level_type was already there.
=> Fix initial waterlevel file if it is empty string

CHANGES.rst, threedi_modelchecker/config.py
@martijn-siemerink  For instance hekerbeekdal has this issue, while there are no numerical problems. @Jonasvsl thinks it is better to make this a warning and don't block threedimodel creation if this happens.
=> Allow isolated unconnected manholes

setup.py
Currently, when running threedi_modelchecker in the console, an error is thrown:
`ImportError: cannot import name 'threedi_modelchecker' from 'threedi_modelchecker.scripts'`
because the function being imported has been renamed to `main`. This commit fixes the issue by updating the import name.
=> fix console script path

CHANGES.rst, threedi_modelchecker/config.py
This PR adds a level check to ensure that the crest level of a weir or orifice is higher than or equal to the bottom level of the manholes it is connected to.
=> 244 confirm that crest level of weir orifice is higher than bottom level of manhole

CHANGES.rst, threedi_modelchecker/checks/other.py, threedi_modelchecker/config.py, threedi_modelchecker/tests/test_checks_other.py
Add check to confirm that the bottom_level of a manhole is higher than the reference_level of the closest cross-section on a connected channel. Since this issue will be fixed anyway in threedigrid-builder, the message level of this check is INFO, not WARNING; no further user action is required.
=> 271 channel manhole level check

CHANGES.rst, setup.py, threedi_modelchecker/exporters.py, threedi_modelchecker/scripts.py, threedi_modelchecker/tests/test_exporters.py
This PR adds a command to export a list of all checks run by the model checker, either as an RsT table or in CSV format. The output can be written to stdout or dumped to a file.
=> 279 make cli generate check summary for docs

CHANGES.rst, threedi_modelchecker/config.py
If a record in the v2_simple_infiltration table exists but is not referenced from v2_global_settings, this gives an info message notifying the user.
=> 168 user has infiltration rasters defined but no simple infiltration referral in the global settings

threedi_modelchecker/checks/raster.py, threedi_modelchecker/config.py, threedi_modelchecker/tests/test_checks_raster.py
This check raises an error if
- `RasterInterface.pixel_size` is `None`
- `GlobalSettings.grid_space` is not an even multiple of `RasterInterface.pixel_size`
- `GlobalSettings.grid_space` is less than 2× `RasterInterface.pixel_size`
=> 227 compare global settings grid size with the dem cell size

CHANGES.rst, threedi_modelchecker/checks/other.py, threedi_modelchecker/config.py, threedi_modelchecker/tests/test_checks_other.py
This check raises a WARNING if a pumpstation is configured such that it will empty its storage in less than one simulation timestep, since that can lead to simulation instabilities.
=> 245 check storage area at node pump is sufficient empty pump cellar in some time not one timestep

CHANGES.rst, threedi_modelchecker/checks/timeseries.py, threedi_modelchecker/config.py, threedi_modelchecker/tests/test_checks_timeseries.py
Adds two checks, both with error code 1206. The first check checks if the timesteps in all timeseries in a column are the same; the second check checks if the timesteps for the timeseries in the first 1D and 2D boundary conditions are the same.
=> 1774 all boundary condition timeseries need to have the same timestamps

threedi_modelchecker/checks/other.py, threedi_modelchecker/config.py, threedi_modelchecker/tests/test_checks_other.py
Reverts nens/threedi-modelchecker#300. I accidentally merged the wrong PR.
=> Revert "243 check inflow area per connection node if larger than x m2 then a warning saying that the user should check storage in the node"

threedi_modelchecker/checks/other.py, threedi_modelchecker/config.py, threedi_modelchecker/tests/test_checks_other.py
Check if all aggregation timesteps are the same, and if they are greater or equal to the global output timestep. Raise a warning if this is not the case.
=> add checks for aggregation timesteps

CHANGES.rst, threedi_modelchecker/checks/other.py, threedi_modelchecker/tests/test_checks_other.py
This was leading to a bug where all pumpstattions were giving an error.
=> fix incorrect units in pumpstation check 66

CHANGES.rst, threedi_modelchecker/config.py
Addresses [this comment](https://github.com/nens/threedi-modelchecker/issues/291#issuecomment-1554339703) by Leendert on #291. Adds a check, 327, which errors if vegetation drag is used with any friction type other than Chézy.
=> Vegetation drag friction type check

threedi_modelchecker/config.py
Unfortunately the conveyance check, 27, currently errors on all cross-section locations. This PR fixes it so it only errors on cross-section locations where friction with conveyance is incorrectly used.
=> fix over-eager conveyance check

CHANGES.rst, threedi_modelchecker/config.py
Check 325 was giving a warning whenever an interception file was used in the global settings.
=> Fix check 325

CHANGES.rst, threedi_modelchecker/checks/base.py, threedi_modelchecker/checks/cross_section_definitions.py, threedi_modelchecker/exporters.py, threedi_modelchecker/tests/test_checks_base.py, threedi_modelchecker/tests/test_exporters.py
This PR orders errors messages and lists within error message descriptions so that the checks overview is consistently ordered the same way. Previously, the output order was random, and therefore updating threedi-modelchecker could cause a large diff in threedi-docs.
=> Order check descriptions

CHANGES.rst, pyproject.toml, threedi_modelchecker/__init__.py, threedi_modelchecker/checks/cross_section_definitions.py, threedi_modelchecker/checks/other.py, threedi_modelchecker/config.py, threedi_modelchecker/tests/test_checks_cross_section_definitions.py, threedi_modelchecker/tests/test_checks_other.py
I added a load of checks. See detailed description below (ticket was not very clear). Note that the contents of these checks needs to be double checked by @GolnesaK or @nvolp.
Note that the tests fail because threedi-schema 0.219 hasn't been released, see https://github.com/nens/threedi-schema/pull/51.
The added checks involve variable friction, vegetation and variable vegetation.
* table: `CrossSectionDefinition`
* columns: `friction_values`, `vegetation_drag_coefficients`, `vegetation_heights`, `vegetation_stem_diameters`, `vegetation_stem_densities`
* conditions:
* string is space-separated
* each element can be converted to a float
* effect: raise error
* table: `CrossSectionDefinition`
* columns: `friction_values`, `vegetation_drag_coefficients`, `vegetation_heights`, …
=> Add checks related to vegetation and variable friction

CHANGES.rst, threedi_modelchecker/checks/cross_section_definitions.py, threedi_modelchecker/config.py
2 sets of changes:
1. Copied checks for Manning friction value >= 1 and modified it to work for Chezy friction
2. Added check for `CrossSectionDefinition.friction_values` and added optional message to `CrossSectionVariableRangeCheck` that overwrites the automatic message.
=> Add checks for Chezy friction value(s) <= 1

pyproject.toml, threedi_modelchecker/checks/other.py, threedi_modelchecker/config.py, threedi_modelchecker/tests/factories.py, threedi_modelchecker/tests/test_checks_other.py
- Modify tests for changed table names
- Modify tests for removed `measure_variable` columns for `table_control` and `memory_control`
- Add test to ensure that only one type of `measure_variable` is associated to a single control
=> Structure control migration fix ups

CHANGES.rst, pyproject.toml, threedi_modelchecker/__init__.py, threedi_modelchecker/checks/base.py, threedi_modelchecker/checks/cross_section_definitions.py, threedi_modelchecker/checks/factories.py, threedi_modelchecker/checks/other.py, threedi_modelchecker/config.py, threedi_modelchecker/tests/factories.py, threedi_modelchecker/tests/test_checks_base.py, threedi_modelchecker/tests/test_checks_cross_section_definitions.py, threedi_modelchecker/tests/test_checks_factories.py, threedi_modelchecker/tests/test_checks_other.py
First of all apologies to the reviewer for the size of this PR. This could have been handled better with smaller PRs on a feature branch; but hindsight is 20 20. I made an overview below, but it's probably best to review together.
The `CrossSectionDefinition` was moved to linked tables: `CrossSectionLocation`, `Culvert', `Orifice`, `Pipe`, `Weir`. Therefore, all checks related to `CrossSectionDefinition` had to be modified an many checks for `CrossSectionLocation` had to be extended to the other four tables.
Several cross section parameters were moved or reformatted:
* `cross_section_width` and `cross_section_height` now only contain a single float. In case of a tabulated shape, the height and width (or Y and Z) are in a csv table in `cross_section_table`. 
* `vegetation_stem_densities`, …
=> upgrade 1D

CHANGES.rst, threedi_modelchecker/checks/location.py, threedi_modelchecker/checks/other.py, threedi_modelchecker/config.py, threedi_modelchecker/tests/factories.py, threedi_modelchecker/tests/test_checks_location.py, threedi_modelchecker/tests/test_checks_other.py
This PR adds a lot of checks that ensure that the geometries of objects match to the objects they are linked to. E.g. wether the geometry of a Pipe matches the line between the two connection nodes it connects. 
For this I generalized LinestringLocationCheck to check for all linestrings. To limit complexity in config.py and to improve testability I created several subclasses for specific cases. For points I renamed CrossSectionLocationCheck to PointLocationCheck and generalized that check. These new / modified checks are moved to a new file (`location.py`). 
~Note I'm waiting for confirmation from Leendert that all new checks should be errors.~ Not going to wait, this can be fixed later.
=> Add geometry match checks

CHANGES.rst, threedi_modelchecker/checks/other.py, threedi_modelchecker/config.py, threedi_modelchecker/tests/test_checks_other.py
* Changed check message
* Used correct value when invoking check
* Update tests and ensure stuff works in a proper way
=> Adapt ConnectionNodeCheck to match projected crs in meters

CHANGES.rst, pyproject.toml, threedi_modelchecker/checks/location.py, threedi_modelchecker/checks/other.py, threedi_modelchecker/config.py, threedi_modelchecker/tests/factories.py, threedi_modelchecker/tests/test_checks_factories.py, threedi_modelchecker/tests/test_checks_location.py, threedi_modelchecker/tests/test_checks_other.py
See https://github.com/nens/threedi-schema/pull/172
=> Adapt to match some name changes in threedi-schema

CHANGES.rst, threedi_modelchecker/checks/base.py, threedi_modelchecker/checks/other.py, threedi_modelchecker/checks/raster.py, threedi_modelchecker/tests/factories.py, threedi_modelchecker/tests/test_checks_base.py, threedi_modelchecker/tests/test_checks_other.py, threedi_modelchecker/tests/test_checks_raster.py, threedi_modelchecker/tests/test_checks_timeseries.py
A whole bunch of references to `session.epsg_ref_name` and `session.epsg_ref_code` were incorrect. It worries me a bit that this is not covered by the tests, but that should be fixed later.
=> Fix typos when referring to epsg_ref_name and epsg_ref_code

.pre-commit-config.yaml, CHANGES.rst, threedi_modelchecker/checks/cross_section_definitions.py, threedi_modelchecker/checks/other.py, threedi_modelchecker/config.py
46 -> FUTURE_ERROR
800 -> FUTURE_ERROR (speciaal voor Olof zijn geheugen)
- 28 
- 186
- 1601
- 1602
- 1603
- 24/25 -> gelden niet meer als 1601-1603 waar zijn. (relationele checks)
- 80 -> spatie in de text (description)
- 87 -> description {self.table.name} kan wel weg.
109 -> manhole bestaat niet meer -> connectionnode
- 623 -> add up to 100 %
- 181, 196 -> na ";" kan weg
- 95/96/97 -> voor culvert, orfice, pipes, weir mag er geen YZ profile worden gezet. (alleen bij channels wel)
=> processed review comments from Nici for modelchecker

CHANGES.rst, threedi_modelchecker/exporters.py, threedi_modelchecker/tests/test_exporters.py
To easily collect errors in the MI with geometry I added a new exporter that returns a named tuple (`ErrorWithGeom`) that contains all information the MI needs.
Usage:
```
modelchecker = ThreediModelChecker(schema.db)
errors = modelchecker.errors()
result = export_with_geom(errors)
```
=> Add exporter that includes geometry related to error

CHANGES.rst, threedi_modelchecker/config.py
Checks were blocked in execution of the sqlite when all of the rows with friction type and friction value None did not refer to a material_id. Changing the query fixes this issue. Note that such a row is invalid, but already caught by another check.
=> Fix problem with checks 1604 and 1605

CHANGES.rst, threedi_modelchecker/checks/cross_section_definitions.py, threedi_modelchecker/tests/test_checks_cross_section_definitions.py
This pull request addresses an issue where empty cross-section tables in `cross_section_configuration_for_record` caused parsing errors. The implementation ensures that `None` is returned for empty tables, improving the robustness of the system alongside `CrossSectionNullCheck`. Note that this issue does not exist in any other cases where `cross_section_table` is parsed because in those instances records with `None` and empty `cross_section_table` fields are filtered out. 
Additionally, a test has been added to reproduce the bug and confirm that it is resolved.
=> Handle empty cross-section tables in record parsing

CHANGES.rst, pyproject.toml, threedi_modelchecker/checks/timeseries.py, threedi_modelchecker/config.py, threedi_modelchecker/tests/test_checks_timeseries.py
Introduced `TimeUnitsValidCheck` to validate time unit formats in timeseries data against `parse_timeunits` from pint. `TimeUnitsValidCheck` is used in check 1207 for boundary_condition_1d, boundary_condition_2d, lateral_1d and lateral_2d.
=> Add TimeUnitsValidCheck for timeseries validation

CHANGES.rst, threedi_modelchecker/config.py
Tested with:
```python
def test_check_manual(session):
factories.ModelSettingsFactory()
factories.ConnectionNodeFactory(id=1, geom=f"SRID={SRID};POINT({POINT1})", )
factories.ConnectionNodeFactory(id=2, geom=f"SRID={SRID};POINT({POINT1})", exchange_type=1)
factories.ConnectionNodeFactory(id=3, geom=f"SRID={SRID};POINT({POINT1})", exchange_type=1, storage_area=0.0)
factories.ConnectionNodeFactory(id=4, geom=f"SRID={SRID};POINT({POINT1})", exchange_type=1, storage_area=-1)
factories.ConnectionNodeFactory(id=5, geom=f"SRID={SRID};POINT({POINT1})", exchange_type=0, storage_area=-1)
check = QueryCheck(
error_code=45,
column=models.ConnectionNode.id,
invalid=Query(models.ConnectionNode)
.filter(
or_(
models.ConnectionNode.storage_area.is_(None),
models.ConnectionNode.storage_area < 0,
)
) …
```
=> Add filter exclude embedded notes from check 45

CHANGES.rst, threedi_modelchecker/checks/other.py, threedi_modelchecker/exporters.py, threedi_modelchecker/tests/test_exporters.py
- Adjusted the geometry exporter to only include geometry when it is an WKB object
- Modify ConnectionNodesDistance check to resturn a WKB object
=> Fix geometry exporter to handle WKB format in error rows

CHANGES.rst, threedi_modelchecker/checks/other.py, threedi_modelchecker/config.py, threedi_modelchecker/tests/test_checks_other.py
This pull request modifies the logic for checking settings' tables to handle cases where data exists but the related "use" settings are not enabled. The `UsedSettingsPresentCheck` class has been generalized and renamed to `SettingsPresentCheck`, with two derived classes, `UsedSettingsPresentCheck` and `UnusedSettingsPresentCheck`, for specific use cases.
=> Add warning for settings tables that contain data but related use settings is not True

CHANGES.rst, threedi_modelchecker/exporters.py, threedi_modelchecker/tests/test_exporters.py
Convert `value` attribute to WKT string to prevent surpising when other code uses the exporters. Including this in the test required a lot of mocking because we don't have shapely in the modelchecker and I didn't want to use geoalchemy to create data.
=> Convert WKB value attributes to WKT
