nens/threedi-modelchecker

- CHANGES.md
- tests/test_checks_base.py
- tests/test_checks_other.py
- threedi_modelchecker/checks/other.py
- Check that width/height are not null
- Height of tabulated shape must be increasing
- Egg only expects width, which is one float
> Updated CrossSectionDefinitionCheck

- CHANGES.rst
- Docker/Dockerfile
- README.rst
- requirements-dev.txt
- setup.cfg
- tests/test_checks_base.py
- threedi_modelchecker/checks/base.py
- threedi_modelchecker/checks/factories.py
- threedi_modelchecker/config.py
- threedi_modelchecker/model_checks.py
- threedi_modelchecker/threedi_model/custom_types.py
- threedi_modelchecker/threedi_model/models.py
Removed `ContitionalCheck` and start with type hints.
> Richard ContitionalCheck and type hints

- CHANGES.rst
- tests/conftest.py
- tests/test_checks_base.py
- tests/test_checks_other.py
- threedi_modelchecker/checks/base.py
- threedi_modelchecker/checks/other.py
- threedi_modelchecker/config.py
- threedi_modelchecker/threedi_model/models.py
closes https://github.com/nens/ThreeDiToolbox/issues/480
closes https://github.com/nens/ThreeDiToolbox/issues/477
closes https://github.com/nens/ThreeDiToolbox/issues/483
> Richard more checks

- CHANGES.rst
- threedi_modelchecker/config.py
closes https://github.com/nens/threedi-modelchecker/issues/25
> Bugfix Pumpstation.lower_stop_level

- threedi_modelchecker/checks/base.py
- threedi_modelchecker/config.py
closes https://github.com/nens/threeditoolbox/issues/513
> Add check to see a connection_node is connected to an artifact

- threedi_modelchecker/checks/base.py
- threedi_modelchecker/config.py
closes https://github.com/nens/threeditoolbox/issues/519
> Richard isolated pipe storage area

- tests/factories.py
- tests/test_checks_other.py
- threedi_modelchecker/checks/base.py
- threedi_modelchecker/checks/other.py
- threedi_modelchecker/config.py
closes https://github.com/nens/threeditoolbox/issues/522
> Richard nested newton

- threedi_modelchecker/threedi_model/models.py
v2_impervious_surface
v2_obstacle
v2_cross_section_location
v2_connection_nodes
v2_grid_refinement
v2_surface
v2_2d_boundary_conditions
v2_2d_lateral
closes https://github.com/nens/threeditoolbox/issues/520
> [done] set the_geom of the following columns to non-nullable:

- CHANGES.rst
- tests/test_checks_other.py
- threedi_modelchecker/checks/other.py
- threedi_modelchecker/config.py
related issue: https://github.com/nens/threeditoolbox/issues/508
> [DONE] ConnectionNodesDistance check

- CHANGES.rst
- setup.cfg
- threedi_modelchecker/threedi_database.py
> Add session_scope context manager

- .gitignore
- rfc/0001.md
- setup.cfg
I put the RFC in a pull request because it is then easy to review. The format is copied from https://github.com/nens/rfcs-for-lizard
> RFC: Use this repo for all sqlite data I/O

- CHANGES.rst
- threedi_modelchecker/config.py
@arnoldvantveld  I have no idea why I can't request a review from  you. But please have a look at this implementation.
> Fix pumpstation.lower_stop_level check

- threedi_modelchecker/checks/other.py
- threedi_modelchecker/config.py
Should this be an error or a warning?
> [Done] Add cross section location geometry check

- docker-compose.yml
- tests/data/postgres/emtpy_postgres.sql
- tests/factories.py
- tests/test_checks_base.py
- tests/test_checks_factories.py
- tests/test_checks_other.py
- threedi_modelchecker/checks/base.py
- threedi_modelchecker/checks/factories.py
- threedi_modelchecker/checks/other.py
- threedi_modelchecker/config.py
- threedi_modelchecker/migrations/versions/0200_initial.py
- threedi_modelchecker/migrations/versions/0202_remove_unused_tables.py
- threedi_modelchecker/migrations/versions/0203_remove_unused_cols.py
- threedi_modelchecker/migrations/versions/0204_reset_nullable_foreign_keys.py
- threedi_modelchecker/threedi_model/models.py
After testing the modelchecker against a bunch models, some things came up.
> [Done] Last fixes

- .github/workflows/test.yml
- CHANGES.rst
- setup.py
- tests/test_simulaton_templates.py
- threedi_modelchecker/simulation_templates/__init__.py
- threedi_modelchecker/simulation_templates/exceptions.py
- threedi_modelchecker/simulation_templates/extractor.py
- threedi_modelchecker/simulation_templates/initial_waterlevels/extractor.py
- threedi_modelchecker/simulation_templates/laterals/extractor.py
- threedi_modelchecker/simulation_templates/models.py
- threedi_modelchecker/simulation_templates/settings/extractor.py
- threedi_modelchecker/simulation_templates/structure_controls/extractor.py
> [DONE] Save simulation template to API 

- CHANGES.rst
- tests/test_simulaton_templates.py
- threedi_modelchecker/simulation_templates/initial_waterlevels/extractor.py
- threedi_modelchecker/simulation_templates/models.py
> [DONE] 2D and gw initial waterlevel support

- CHANGES.rst
- threedi_modelchecker/migrations/versions/0205_settings_defaults.py
Ref. https://github.com/nens/threedi-api/issues/1252
> Fix maximum_time_step

- tests/test_checks_base.py
- threedi_modelchecker/checks/base.py
- threedi_modelchecker/config.py
There were some unreadable error messages (that were actually SQL queries). I gave these a proper description.
> Replace GeneralCheck

- CHANGES.rst
- tests/factories.py
- threedi_modelchecker/migrations/versions/0212_breach_and_exchange_properties.py
- threedi_modelchecker/migrations/versions/0213_connected_points_to_breaches.py
- threedi_modelchecker/migrations/versions/0214_drop_cpoints_levees.py
- threedi_modelchecker/threedi_model/models.py
This migration resets the levee ids (this was easiest) before merging them into v2_obstacle.
> Cleaning migration

- threedi_modelchecker/checks/other.py
> fix keyword arguments for ConnectionNodesDistance and OpenChannelsWithNestedNewton

- threedi_modelchecker/checks/raster.py
- threedi_modelchecker/config.py
- threedi_modelchecker/interfaces/raster_interface.py
- threedi_modelchecker/interfaces/raster_interface_gdal.py
- threedi_modelchecker/interfaces/raster_interface_rasterio.py
- threedi_modelchecker/tests/test_checks_raster.py
Raise WARNING when the EPSG code in the global settings does not match the one in the DEM.
> 228 compare global settings epsg code with the dem crs

- CHANGES.rst
- setup.py
- threedi_modelchecker/checks/timeseries.py
- threedi_modelchecker/config.py
- threedi_modelchecker/tests/test_checks_timeseries.py
This is also the case for laterals.
> 286 time series empty for boundary conditions should not be allowed

- threedi_modelchecker/checks/other.py
- threedi_modelchecker/config.py
- threedi_modelchecker/tests/test_checks_other.py
This is a new pull request to replace the one that was accidentally merged and reverted.
> 243 check inflow area per connection node if larger than x m2 then a warning saying that the user should check storage in the node

- CHANGES.rst
- threedi_modelchecker/config.py
- threedi_modelchecker/model_checks.py
- threedi_modelchecker/scripts.py
This PR adds support for ignoring certain checks by passing in a regex; matching checks will be ignored. The reasoning behind this is explained in the linked issue.
> Add argument for ignoring certain check codes

- CHANGES.rst
- threedi_modelchecker/config.py
from ERROR to WARNING
Plus some improved formatting in CHANGES.rst
> Log level of check 63 to WARNING

- .github/workflows/release.yml
This PR triggers the schematisation checks update workflow in nens/threedi-docs. Note that the token (which is stored in the threedi-modelchecker repo settings) will expire on 18/01/2025!
> Trigger docs pr

- CHANGES.rst
- pyproject.toml
- threedi_modelchecker/checks/base.py
- threedi_modelchecker/checks/other.py
- threedi_modelchecker/config.py
- threedi_modelchecker/tests/factories.py
- threedi_modelchecker/tests/test_checks_base.py
- threedi_modelchecker/tests/test_checks_other.py
See zenhub issue for full details of the migration
This migration adds tags to the schema. Tags are stored in a dedicated table with an id and description. Any table with a geometry has a tags field that contains a list of integers that refer to the ids in the tags table. This is checked with check 2xxx:
* `ListOfIntsCheck`
* `TagsValidCheck`
Tested with included tests and https://github.com/nens/schema_300_integration_tests
> inflow schema 300

- CHANGES.rst
- pyproject.toml
- threedi_modelchecker/config.py
Modify modelchecker for requested name changes
> Fix 79 schema 224 bugs

- CHANGES.rst
- threedi_modelchecker/config.py
Forgot to add some tables to the checks related to tags.
> Add missing checks for tags

- CHANGES.rst
- pyproject.toml
- threedi_modelchecker/checks/other.py
- threedi_modelchecker/config.py
- threedi_modelchecker/tests/test_checks_other.py
Note that this is not based on master. The parent branch contains some minor fixes to work with the current state of schema.
> Check use fields

- CHANGES.rst
- pyproject.toml
- threedi_modelchecker/checks/other.py
- threedi_modelchecker/tests/factories.py
- threedi_modelchecker/tests/test_checks_base.py
- threedi_modelchecker/tests/test_checks_other.py
- threedi_modelchecker/tests/test_checks_timeseries.py
Changes
* Enforce unique non null id's in factories
* Ensure items are ordered when expected (timeseries)
* Change tests that use `SpatialIndex`
> Fix modelchecker tests for geopackage

- CHANGES.rst
- pyproject.toml
- threedi_modelchecker/checks/other.py
Note that this requires schema version 0.300 with patch version 1 or higher!
> fix table name tags

- CHANGES.rst
- threedi_modelchecker/tests/factories.py
- threedi_modelchecker/tests/test_checks_timeseries.py
see connected ticket for problem description
> Ensure autoincrement pk in model factories

- CHANGES.rst
- threedi_modelchecker/config.py
please see the comment on the issue
> fix check 107
